version: '3.8'
services:
  migrations-db:
    container_name: migrations_db
    image: postgres:latest
    environment:
      POSTGRES_DB: "migration_test"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres
  pgadmin-migrations:
    container_name: pgadmin4_migrations
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - postgres
networks:
  postgres:
    driver: bridge